[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20"
  NEXT_PUBLIC_APP_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
